// cards.jsx

const cards = [
  {
    id: "R1",
    name: "Strong Start",
    class: "Red",
    text: "Move forward 1, if the racer is in the 1st Quarter of the Track, move forward 2",
    cardCode: "M,S,1-if-SST-then-M,S,2",
    cost: 1,
  },
  {
    id: "R2",
    name: "In Your Stride",
    class: "Red",
    text: "Move forward 1, if the racer is in the 2nd Quarter of the Track, move forward 2",
    cardCode: "M,S,1-if-SEM-then-M,S,2",
    cost: 1,
  },
  {
    id: "R3",
    name: "Late Rhythm",
    class: "Red",
    text: "Move forward 1, if the racer is in the 3rd Quarter of the Track, move forward 2",
    cardCode: "M,S,1-if-SLM-then-M,S,2",
    cost: 1,
  },
  {
    id: "R4",
    name: "Final Pace",
    class: "Red",
    text: "Move forward 1, if the racer is in the 4th Quarter of the Track, move forward 2",
    cardCode: "M,S,1-if-SED-then-M,S,2",
    cost: 1,
  },
  {
    id: "R5",
    name: "Red First-Half Drive",
    class: "Red",
    text: "Move forward 1, if the Class is Red and the racer is in the first half of the track, move forward 3",
    cardCode: "M,S,1-if-CLR-and-HAF-then-M,S,3",
    cost: 1,
  },
  {
    id: "R6",
    name: "Red Second-Half Drive",
    class: "Red",
    text: "Move forward 1, if the Class is Red and the racer is in the second half of the track, move forward 3",
    cardCode: "M,S,1-if-CLR-and-HAS-then-M,S,3",
    cost: 1,
  },
  {
    id: "R7",
    name: "Red Midrace Drive",
    class: "Red",
    text: "Move forward 1, if the Class is Red and the racer is in the middle of the track, move forward 3",
    cardCode: "M,S,1-if-CLR-and-HAM-then-M,S,3",
    cost: 1,
  },
  {
    id: "R8",
    name: "Red Edge Burst",
    class: "Red",
    text: "Move forward 1, if the Class is Red and the racer is in the start or end of the track, move forward 3",
    cardCode: "M,S,1-if-CLR-and-HAE-then-M,S,3",
    cost: 1,
  },
  {
    id: "R9",
    name: "Early Runner",
    class: "Red",
    text: "Move forward 1, if the racer is in the first half of the track, move forward 2",
    cardCode: "M,S,1-if-HAF-then-M,S,2",
    cost: 2,
  },
  {
    id: "R10",
    name: "Late Runner",
    class: "Red",
    text: "Move forward 1, if the racer is in the second half of the track, move forward 2",
    cardCode: "M,S,1-if-HAS-then-M,S,2",
    cost: 2,
  },
  {
    id: "R11",
    name: "Midrace Runner",
    class: "Red",
    text: "Move forward 1, if the racer is in the middle of the track, move forward 2",
    cardCode: "M,S,1-if-HAM-then-M,S,2",
    cost: 2,
  },
  {
    id: "R12",
    name: "Edge Runner",
    class: "Red",
    text: "Move forward 1, if the racer is in the start or end of the track, move forward 2",
    cardCode: "M,S,1-if-HAE-then-M,S,2",
    cost: 2,
  },
  {
    id: "R13",
    name: "Explosive Start",
    class: "Red",
    text: "Move forward 2, if the racer is in the 1st Quarter of the Track, move forward 5.",
    cardCode: "M,S,2-if-SST-then-M,S,5",
    cost: 3,
  },
  {
    id: "R14",
    name: "Breaking Pace",
    class: "Red",
    text: "Move forward 2, if the racer is in the 2nd Quarter of the Track, move forward 5",
    cardCode: "M,S,2-if-SEM-then-M,S,5",
    cost: 3,
  },
  {
    id: "R15",
    name: "Late Charge",
    class: "Red",
    text: "Move forward 2, if the racer is in the 3rd Quarter of the Track, move forward 5",
    cardCode: "M,S,2-if-SLM-then-M,S,5",
    cost: 3,
  },
  {
    id: "R16",
    name: "Final Surge",
    class: "Red",
    text: "Move forward 2, if the racer is in the 4th Quarter of the Track, move forward 5",
    cardCode: "M,S,2-if-SED-then-M,S,5",
    cost: 3,
  },

  {
    id: "B1",
    name: "Measured Opening",
    class: "Blue",
    text: "Move forward 1, if the racer is in the 1st Quarter of the Track, move forward 1 and get 5 stamina.",
    cardCode: "M,S,1-if-SST-then-M,S,1-S,S,5",
    cost: 1,
  },
  {
    id: "B2",
    name: "Settling In",
    class: "Blue",
    text: "Move forward 1, if the racer is in the 2nd Quarter of the Track, move forward 1 and get 5 stamina.",
    cardCode: "M,S,1-if-SEM-then-M,S,1-S,S,5",
    cost: 1,
  },
  {
    id: "B3",
    name: "Maintained Pace",
    class: "Blue",
    text: "Move forward 1, if the racer is in the 3rd Quarter of the Track, move forward 1 and get 5 stamina.",
    cardCode: "M,S,1-if-SLM-then-M,S,1-S,S,5",
    cost: 1,
  },
  {
    id: "B4",
    name: "Calm Finish",
    class: "Blue",
    text: "Move forward 1, if the racer is in the 4th Quarter of the Track, move forward 1 and get 5 stamina.",
    cardCode: "M,S,1-if-SED-then-M,S,1-S,S,5",
    cost: 1,
  },
  {
    id: "B5",
    name: "Shared Endurance (Red)",
    class: "Blue",
    text: "Move forward 1, if the racer has Stamina and the class is Red, move forward 2",
    cardCode: "M,S,1-if-STA-and-CLR-then-M,S,2",
    cost: 1,
  },
  {
    id: "B6",
    name: "Shared Endurance (Blue)",
    class: "Blue",
    text: "Move forward 1, if the racer has Stamina and the class is Blue, move forward 2",
    cardCode: "M,S,1-if-STA-and-CLB-then-M,S,2",
    cost: 1,
  },
  {
    id: "B7",
    name: "Shared Endurance (Green)",
    class: "Blue",
    text: "Move forward 1, if the racer has Stamina and the class is Green, move forward 2",
    cardCode: "M,S,1-if-STA-and-CLG-then-M,S,2",
    cost: 1,
  },
  {
    id: "B8",
    name: "Shared Endurance (Yellow)",
    class: "Blue",
    text: "Move forward 1, if the racer has Stamina and the class is Yellow, move forward 2",
    cardCode: "M,S,1-if-STA-and-CLY-then-M,S,2",
    cost: 1,
  },
  {
    id: "B9",
    name: "Shared Endurance (Orange)",
    class: "Blue",
    text: "Move forward 1, if the racer has Stamina and the class is Orange, move forward 2",
    cardCode: "M,S,1-if-STA-and-CLO-then-M,S,2",
    cost: 1,
  },
  {
    id: "B10",
    name: "Deep Reserves (Early)",
    class: "Blue",
    text: "Get 10 Stamina, if the racer is in the first half of the track, get 10 Stamina and move forward 1",
    cardCode: "S,S,10-if-HAF-then-S,S,10-M,S,1",
    cost: 2,
  },
  {
    id: "B11",
    name: "Deep Reserves (Late)",
    class: "Blue",
    text: "Get 10 Stamina, if the racer is in the second half of the track, get 10 Stamina and move forward 1",
    cardCode: "S,S,10-if-HAS-then-S,S,10-M,S,1",
    cost: 2,
  },
  {
    id: "B12",
    name: "Deep Reserves (Midrace)",
    class: "Blue",
    text: "Get 10 Stamina, if the racer is in the middle of the track, get 10 Stamina and move forward 1",
    cardCode: "S,S,10-if-HAM-then-S,S,10-M,S,1",
    cost: 2,
  },
  {
    id: "B13",
    name: "Deep Reserves (Edges)",
    class: "Blue",
    text: "Get 10 Stamina, if the racer is in the start or end of the track, get 10 Stamina and move forward 1",
    cardCode: "S,S,10-if-HAE-then-S,S,10-M,S,1",
    cost: 2,
  },
  {
    id: "B14",
    name: "Team Wind (Early)",
    class: "Blue",
    text: "Move forward 3 and get 10 Stamina, if the racer is in the first half of the track, all other racers get 3 Stamina too",
    cardCode: "M,S,3-S,S,10-if-HAF-then-M,S,3-S,S,10-S,AO,3",
    cost: 3,
  },
  {
    id: "B15",
    name: "Team Wind (Late)",
    class: "Blue",
    text: "Move forward 3 and get 10 Stamina, if the racer is in the second half of the track, all other racers get 3 Stamina too",
    cardCode: "M,S,3-S,S,10-if-HAS-then-M,S,3-S,S,10-S,AO,3",
    cost: 3,
  },
  {
    id: "B16",
    name: "Blue Second Wind",
    class: "Blue",
    text: "Move forward 2, if the racer has Stamina and the class is Blue, move forward 4 and get 5 stamina",
    cardCode: "M,S,2-if-STA-and-CLB-then-M,S,4-S,S,5",
    cost: 3,
  },

  {
    id: "G1",
    name: "Front-Runner Pressure",
    class: "Green",
    text: "Move forward 1, if the racer is in First place, move forward 3",
    cardCode: "M,S,1-if-FIRP-then-M,S,3",
    cost: 1,
  },
  {
    id: "G2",
    name: "Chasing Pressure",
    class: "Green",
    text: "Move forward 1, if the racer is in Second place, move forward 3",
    cardCode: "M,S,1-if-SECP-then-M,S,3",
    cost: 1,
  },
  {
    id: "G3",
    name: "Pack Pressure",
    class: "Green",
    text: "Move forward 1, if the racer is in Third place, move forward 3",
    cardCode: "M,S,1-if-THRP-then-M,S,3",
    cost: 1,
  },
  {
    id: "G4",
    name: "Last-Push Pressure",
    class: "Green",
    text: "Move forward 1, if the racer is in Fourth place, move forward 3",
    cardCode: "M,S,1-if-FORP-then-M,S,3",
    cost: 1,
  },
  {
    id: "G5",
    name: "Lead Strain",
    class: "Green",
    text: "Move forward 2, if the racer is in First place, move forward 2 and get 5 Fatigue",
    cardCode: "M,S,2-if-FIRP-then-M,S,2-F,S,5",
    cost: 1,
  },
  {
    id: "G6",
    name: "Chasing Strain",
    class: "Green",
    text: "Move forward 2, if the racer is in Second place, move forward 2 and get 5 Fatigue",
    cardCode: "M,S,2-if-SECP-then-M,S,2-F,S,5",
    cost: 1,
  },
  {
    id: "G7",
    name: "Mid-Pack Strain",
    class: "Green",
    text: "Move forward 2, if the racer is in Third place, move forward 2 and get 5 Fatigue",
    cardCode: "M,S,2-if-THRP-then-M,S,2-F,S,5",
    cost: 1,
  },
  {
    id: "G8",
    name: "Last Stand Strain",
    class: "Green",
    text: "Move forward 2, if the racer is in Fourth place, move forward 2 and get 5 Fatigue",
    cardCode: "M,S,2-if-FORP-then-M,S,2-F,S,5",
    cost: 1,
  },
  {
    id: "G9",
    name: "Toxic Opening",
    class: "Green",
    text: "Move forward 2 and get 10 Fatigue, if the racer is in the 1st Quarter of the Track, give everyone else in the 1st Quarter of the Track 5 Fatigue too",
    cardCode: "M,S,2-F,S,10-if-SST-then-M,S,2-F,S,10-F,SS,5",
    cost: 2,
  },
  {
    id: "G10",
    name: "Spreading Exhaustion",
    class: "Green",
    text: "Move forward 2 and get 10 Fatigue, if the racer is in the 2nd Quarter of the Track, give everyone else in the 2nd Quarter of the Track 5 Fatigue too",
    cardCode: "M,S,2-F,S,10-if-SEM-then-M,S,2-F,S,10-F,SS,5",
    cost: 2,
  },
  {
    id: "G11",
    name: "Midrace Contagion",
    class: "Green",
    text: "Move forward 2 and get 10 Fatigue, if the racer is in the 3rd Quarter of the Track, give everyone else in the 1st Quarter of the Track 5 Fatigue too",
    cardCode: "M,S,2-F,S,10-if-SLM-then-M,S,2-F,S,10-F,SS,5",
    cost: 2,
  },
  {
    id: "G12",
    name: "Endgame Contagion",
    class: "Green",
    text: "Move forward 2 and get 10 Fatigue, if the racer is in the 4th Quarter of the Track, give everyone else in the 1st Quarter of the Track 5 Fatigue too",
    cardCode: "M,S,2-F,S,10-if-SED-then-M,S,2-F,S,10-F,SS,5",
    cost: 2,
  },
  {
    id: "G13",
    name: "Selective Collapse (Red)",
    class: "Green",
    text: "Move forward 3 and give everyone 10 Fatigue, if the class is Red, do not give yourself any Fatigue.",
    cardCode: "M,S,3-F,A,10-if-CLR-then-M,S,3-F,AO,10",
    cost: 3,
  },
  {
    id: "G14",
    name: "Selective Collapse (Blue)",
    class: "Green",
    text: "Move forward 3 and give everyone 10 Fatigue, if the class is Blue, do not give yourself any Fatigue.",
    cardCode: "M,S,3-F,A,10-if-CLB-then-M,S,3-F,AO,10",
    cost: 3,
  },
  {
    id: "G15",
    name: "Selective Collapse (Yellow)",
    class: "Green",
    text: "Move forward 3 and give everyone 10 Fatigue, if the class is Yellow, do not give yourself any Fatigue.",
    cardCode: "M,S,3-F,A,10-if-CLY-then-M,S,3-F,AO,10",
    cost: 3,
  },
  {
    id: "G16",
    name: "Selective Collapse (Orange)",
    class: "Green",
    text: "Move forward 3 and give everyone 10 Fatigue, if the class is Orange, do not give yourself any Fatigue.",
    cardCode: "M,S,3-F,A,10-if-CLO-then-M,S,3-F,AO,10",
    cost: 3,
  },

  {
    id: "Y1",
    name: "Grinding Forward",
    class: "Yellow",
    text: "Move forward 1, if the racer has Fatigue, move forward 3.",
    cardCode: "M,S,1-if-FAT-then-M,S,3",
    cost: 1,
  },
  {
    id: "Y2",
    name: "Sweat to Speed",
    class: "Yellow",
    text: "Move forward 1, if the racer has Fatigue, move forward 2 and get 5 stamina",
    cardCode: "M,S,1-if-FAT-then-M,S,2-S,S,5",
    cost: 1,
  },
  {
    id: "Y3",
    name: "Spread the Pain",
    class: "Yellow",
    text: "Move forward 1, if the racer has Fatigue, move forward 1 and give everyone else 5 Fatigue",
    cardCode: "M,S,1-if-FAT-then-M,S,1-F,AO,5",
    cost: 1,
  },
  {
    id: "Y4",
    name: "Crowd Jostle",
    class: "Yellow",
    text: "Move forward 2, move everyone else forward 1, if the racer has Fatigue, move forward 3, move everyone else forward 1 and give them 5 Fatigue",
    cardCode: "M,S,2-M,AO,1-if-FAT-then-M,S,3-M,AO,1-F,AO,5",
    cost: 1,
  },
  {
    id: "Y5",
    name: "Early Breakthrough",
    class: "Yellow",
    text: "Move forward 1, if the racer has Fatigue and is in the first half of the track, move forward 5",
    cardCode: "M,S,1-if-FAT-and-HAF-then-M,S,5",
    cost: 2,
  },
  {
    id: "Y6",
    name: "Late Breakthrough",
    class: "Yellow",
    text: "Move forward 1, if the racer has Fatigue and is in the second half of the track, move forward 5",
    cardCode: "M,S,1-if-FAT-and-HAS-then-M,S,5",
    cost: 2,
  },
  {
    id: "Y7",
    name: "Midrace Breakthrough",
    class: "Yellow",
    text: "Move forward 1, if the racer has Fatigue and is in the middle of the track, move forward 5",
    cardCode: "M,S,1-if-FAT-and-HAM-then-M,S,5",
    cost: 2,
  },
  {
    id: "Y8",
    name: "Edge Breakthrough",
    class: "Yellow",
    text: "Move forward 1, if the racer has Fatigue and is in the start or end of the track, move forward 5",
    cardCode: "M,S,1-if-FAT-and-HAE-then-M,S,5",
    cost: 2,
  },
  {
    id: "Y9",
    name: "Burn for Pace (Start)",
    class: "Yellow",
    text: "Move forward 2, if the racer is in the 1st Quarter of the Track, move forward 3 and get 10 Fatigue",
    cardCode: "M,S,2-if-SST-then-M,S,3-F,S,10",
    cost: 2,
  },
  {
    id: "Y10",
    name: "Burn for Pace (Early-Mid)",
    class: "Yellow",
    text: "Move forward 2, if the racer is in the 2nd Quarter of the Track, move forward 3 and get 10 Fatigue",
    cardCode: "M,S,2-if-SEM-then-M,S,3-F,S,10",
    cost: 2,
  },
  {
    id: "Y11",
    name: "Burn for Pace (Late-Mid)",
    class: "Yellow",
    text: "Move forward 2, if the racer is in the 3rd Quarter of the Track, move forward 3 and get 10 Fatigue",
    cardCode: "M,S,2-if-SLM-then-M,S,3-F,S,10",
    cost: 2,
  },
  {
    id: "Y12",
    name: "Burn for Pace (End)",
    class: "Yellow",
    text: "Move forward 2, if the racer is in the 4th Quarter of the Track, move forward 3 and get 10 Fatigue",
    cardCode: "M,S,2-if-SED-then-M,S,3-F,S,10",
    cost: 2,
  },
  {
    id: "Y13",
    name: "Punishing Burst (Red)",
    class: "Yellow",
    text: "Move forward 3, if the racer has Fatigue and the class is Red, move forward 6 and give everyone else 10 Fatigue",
    cardCode: "M,S,3-if-FAT-and-CLR-then-M,S,6-F,AO,10",
    cost: 3,
  },
  {
    id: "Y14",
    name: "Punishing Burst (Blue)",
    class: "Yellow",
    text: "Move forward 3, if the racer has Fatigue and the class is Blue, move forward 6 and give everyone else 10 Fatigue",
    cardCode: "M,S,3-if-FAT-and-CLB-then-M,S,6-F,AO,10",
    cost: 3,
  },
  {
    id: "Y15",
    name: "Punishing Burst (Green)",
    class: "Yellow",
    text: "Move forward 3, if the racer has Fatigue and the class is Green, move forward 6 and give everyone else 10 Fatigue",
    cardCode: "M,S,3-if-FAT-and-CLG-then-M,S,6-F,AO,10",
    cost: 3,
  },
  {
    id: "Y16",
    name: "Punishing Burst (Orange)",
    class: "Yellow",
    text: "Move forward 3, if the racer has Fatigue and the class is Orange, move forward 6 and give everyone else 10 Fatigue",
    cardCode: "M,S,3-if-FAT-and-CLO-then-M,S,6-F,AO,10",
    cost: 3,
  },

  {
    id: "O1",
    name: "Starting Block Shove",
    class: "Orange",
    text: "Move forward 1, move all racers in the 1st Quarter of the Track backward by 1",
    cardCode: "M,S,1-MB,SST,1",
    cost: 1,
  },
  {
    id: "O2",
    name: "Early Jam",
    class: "Orange",
    text: "Move forward 1, move all racers in the 2nd Quarter of the Track backward by 1",
    cardCode: "M,S,1-MB,SEM,1",
    cost: 1,
  },
  {
    id: "O3",
    name: "Midrace Jam",
    class: "Orange",
    text: "Move forward 1, move all racers in the 3rd Quarter of the Track backward by 1",
    cardCode: "M,S,1-MB,SLM,1",
    cost: 1,
  },
  {
    id: "O4",
    name: "Endgame Stall",
    class: "Orange",
    text: "Move forward 1, move all racers in the 4th Quarter of the Track backward by 1",
    cardCode: "M,S,1-MB,SED,1",
    cost: 1,
  },
  {
    id: "O5",
    name: "Row Wrecker",
    class: "Orange",
    text: "Move forward 1, move all racers in the same row backward by 2",
    cardCode: "M,S,1-MB,SR,2",
    cost: 1,
  },
  {
    id: "O6",
    name: "Red Lockdown",
    class: "Orange",
    text: "Move forward 1, if class is Red, move racers in the same quarter backwards by 2",
    cardCode: "M,S,1-if-CLR-then-M,S,1-MB,SS,2",
    cost: 1,
  },
  {
    id: "O7",
    name: "Blue Lockdown",
    class: "Orange",
    text: "Move forward 1, if class is Blue, move racers in the same quarter backwards by 2",
    cardCode: "M,S,1-if-CLB-then-M,S,1-MB,SS,2",
    cost: 1,
  },
  {
    id: "O8",
    name: "Green Lockdown",
    class: "Orange",
    text: "Move forward 1, if class is Green, move racers in the same quarter backwards by 2",
    cardCode: "M,S,1-if-CLG-then-M,S,1-MB,SS,2",
    cost: 1,
  },
  {
    id: "O9",
    name: "Yellow Lockdown",
    class: "Orange",
    text: "Move forward 1, if class is Yellow, move racers in the same quarter backwards by 2",
    cardCode: "M,S,1-if-CLY-then-M,S,1-MB,SS,2",
    cost: 1,
  },
  {
    id: "O10",
    name: "Halfway Pullback (Early)",
    class: "Orange",
    text: "Move everyone else backwards 1, if the racer is in the first half of the track, move forward 2",
    cardCode: "MB,AO,1-if-HAF-then-MB,AO,1-M,S,2",
    cost: 2,
  },
  {
    id: "O11",
    name: "Halfway Pullback (Late)",
    class: "Orange",
    text: "Move everyone else backwards 1, if the racer is in the second half of the track, move forward 2",
    cardCode: "MB,AO,1-if-HAS-then-MB,AO,1-M,S,2",
    cost: 2,
  },
  {
    id: "O12",
    name: "Halfway Pullback (Midrace)",
    class: "Orange",
    text: "Move everyone else backwards 1, if the racer is in the middle of the track, move forward 2",
    cardCode: "MB,AO,1-if-HAM-then-MB,AO,1-M,S,2",
    cost: 2,
  },
  {
    id: "O13",
    name: "Edge Pullback",
    class: "Orange",
    text: "Move everyone else backwards 1, if the racer is in the start or end of the track, move forward 2",
    cardCode: "MB,AO,1-if-HAE-then-MB,AO,1-M,S,2",
    cost: 2,
  },
  {
    id: "O14",
    name: "Stamina Slam",
    class: "Orange",
    text: "Move forward 2, if the racer has Stamina, move forward 2 and move everyone else back 2",
    cardCode: "M,S,2-if-STA-then-M,S,2-MB,AO,2",
    cost: 3,
  },
  {
    id: "O15",
    name: "Stage Shock (Early)",
    class: "Orange",
    text: "Move everyone in the same quarter back 3, if the racer is in the first half of the track, move forward 1 and get 10 Stamina",
    cardCode: "MB,SS,3-if-HAF-then-MB,SS,3-M,S,1-S,S,10",
    cost: 3,
  },
  {
    id: "O16",
    name: "Stage Shock (Late)",
    class: "Orange",
    text: "Move everyone in the same quarter back 3, if the racer is in the second half of the track, move forward 1 and get 10 Stamina",
    cardCode: "MB,SS,3-if-HAS-then-MB,SS,3-M,S,1-S,S,10",
    cost: 3,
  },
];

export default cards;

