const events = [
  {
    id: "EV1",
    text: "{piece} offered you a chance to win 50 coins.",
    chance: "1",
    rarity: "Common",
    reward: "50 coins",
    secondaryReward: "None",
  },
  {
    id: "EV2",
    text: "{piece} offered you a chance to win 100 coins.",
    chance: "1",
    rarity: "Uncommon",
    reward: "100 coins",
    secondaryReward: "None",
  },
  {
    id: "EV3",
    text: "{piece} offered you a chance to win 200 coins.",
    chance: "1",
    rarity: "Rare",
    reward: "200 coins",
    secondaryReward: "None",
  },
  {
    id: "EV4",
    text: "{piece} offered you a chance to win 500 coins.",
    chance: "1",
    rarity: "Very Rare",
    reward: "500 coins",
    secondaryReward: "None",
  },
  {
    id: "EV5",
    text: "{piece} challenged you for a chance to win 100 coins.",
    chance: "1/2",
    rarity: "Common",
    reward: "100 coins",
    secondaryReward: "None",
  },
  {
    id: "EV6",
    text: "{piece} challenged you for a chance to win 200 coins.",
    chance: "1/2",
    rarity: "Uncommon",
    reward: "200 coins",
    secondaryReward: "None",
  },
  {
    id: "EV7",
    text: "{piece} challenged you for a chance to win 500 coins.",
    chance: "1/2",
    rarity: "Rare",
    reward: "500 coins",
    secondaryReward: "None",
  },
  {
    id: "EV8",
    text: "{piece} challenged you for a chance to win 1000 coins.",
    chance: "1/2",
    rarity: "Very Rare",
    reward: "1000 coins",
    secondaryReward: "None",
  },
  {
    id: "EV9",
    text: "{piece} tempted you with a risky offer for 200 coins.",
    chance: "1/3",
    rarity: "Common",
    reward: "200 coins",
    secondaryReward: "None",
  },
  {
    id: "EV10",
    text: "{piece} tempted you with a risky offer for 500 coins.",
    chance: "1/3",
    rarity: "Uncommon",
    reward: "500 coins",
    secondaryReward: "50 coins",
  },
  {
    id: "EV11",
    text: "{piece} tempted you with a risky offer for 1000 coins.",
    chance: "1/3",
    rarity: "Rare",
    reward: "1000 coins",
    secondaryReward: "50 coins",
  },
  {
    id: "EV12",
    text: "{piece} tempted you with a risky offer for 1500 coins.",
    chance: "1/3",
    rarity: "Very Rare",
    reward: "1500 coins",
    secondaryReward: "50 coins",
  },
  {
    id: "EV13",
    text: "{piece} asked for help finding a lost Class Coin.",
    chance: "1/4",
    rarity: "Uncommon",
    reward: "1 Random Class Coin",
    secondaryReward: "50 coins",
  },
  {
    id: "EV14",
    text: "{piece} asked for help finding a lost Class Coin.",
    chance: "1/3",
    rarity: "Rare",
    reward: "1 Random Class Coin",
    secondaryReward: "50 coins",
  },
  {
    id: "EV15",
    text: "{piece} asked for help finding a lost Class Coin.",
    chance: "1/2",
    rarity: "Very Rare",
    reward: "1 Random Class Coin",
    secondaryReward: "50 coins",
  },
  {
    id: "EV16",
    text: "{piece} offered to reward you with a Class Coin of your choice.",
    chance: "1/4",
    rarity: "Uncommon",
    reward: "1 Class Coin of your Choice",
    secondaryReward: "50 coins",
  },
  {
    id: "EV17",
    text: "{piece} offered to reward you with a Class Coin of your choice.",
    chance: "1/3",
    rarity: "Rare",
    reward: "1 Class Coin of your Choice",
    secondaryReward: "50 coins",
  },
  {
    id: "EV18",
    text: "{piece} offered to reward you with a Class Coin of your choice.",
    chance: "1/2",
    rarity: "Very Rare",
    reward: "1 Class Coin of your Choice",
    secondaryReward: "50 coins",
  },
  {
    id: "EV19",
    text: "{piece} hinted at unlocking a hidden Tier 2 card.",
    chance: "1/4",
    rarity: "Common",
    reward: "Unlock a random Tier 2 card",
    secondaryReward: "50 coins",
  },
  {
    id: "EV20",
    text: "{piece} hinted at unlocking a hidden Tier 2 card.",
    chance: "1/3",
    rarity: "Uncommon",
    reward: "Unlock a random Tier 2 card",
    secondaryReward: "50 coins",
  },
  {
    id: "EV21",
    text: "{piece} hinted at unlocking a hidden Tier 2 card.",
    chance: "1/2",
    rarity: "Rare",
    reward: "Unlock a random Tier 2 card",
    secondaryReward: "50 coins",
  },
  {
    id: "EV22",
    text: "{piece} revealed a guaranteed Tier 2 card.",
    chance: "1",
    rarity: "Very Rare",
    reward: "Unlock a random Tier 2 card",
    secondaryReward: "50 coins",
  },
  {
    id: "EV23",
    text: "{piece} whispered about unlocking a powerful Tier 3 card.",
    chance: "1/4",
    rarity: "Uncommon",
    reward: "Unlock a random Tier 3 card",
    secondaryReward: "100 coins",
  },
  {
    id: "EV24",
    text: "{piece} whispered about unlocking a powerful Tier 3 card.",
    chance: "1/3",
    rarity: "Rare",
    reward: "Unlock a random Tier 3 card",
    secondaryReward: "100 coins",
  },
  {
    id: "EV25",
    text: "{piece} whispered about unlocking a powerful Tier 3 card.",
    chance: "1/2",
    rarity: "Very Rare",
    reward: "Unlock a random Tier 3 card",
    secondaryReward: "100 coins",
  },
];

export default events;
