const themes = [
  {
    id: "dots",
    name: "Dots",
    nameStyle: "pooled",
    namePool: ["Zippy", "Dash", "Nova", "Pixel", "Bolt", "Fizz", "Echo", "Quirk"],
    trackColor: "#cfe8ff",
    iconSize: "small",
    pieces: [
      { id: "dot-red", name: "Red", color: "#ff6b6b", type: "dot" },
      { id: "dot-blue", name: "Blue", color: "#4dabf7", type: "dot" },
      { id: "dot-green", name: "Green", color: "#63e6be", type: "dot" },
      { id: "dot-yellow", name: "Yellow", color: "#ffd43b", type: "dot" },
      { id: "dot-orange", name: "Orange", color: "#ffa94d", type: "dot" },
      { id: "dot-purple", name: "Purple", color: "#b197fc", type: "dot" },
      { id: "dot-pink", name: "Pink", color: "#f783ac", type: "dot" },
      { id: "dot-teal", name: "Teal", color: "#38d9a9", type: "dot" },
    ],
  },
  {
    id: "ghosts",
    name: "Ghosts",
    nameStyle: "pooled",
    namePool: ["Wraith", "Spindle", "Eerie", "Shade", "Grim", "Whisper", "Ghast", "Mourn"],
    trackColor: "#2b3b4c",
    iconSize: "medium",
    pieces: [
      { id: "ghost-1", name: "Ghost 1", color: "#9bbcff", type: "icon", icon: "ghost" },
      { id: "ghost-2", name: "Ghost 2", color: "#b6f0ff", type: "icon", icon: "ghost" },
      { id: "ghost-3", name: "Ghost 3", color: "#f0b3ff", type: "icon", icon: "ghost" },
      { id: "ghost-4", name: "Ghost 4", color: "#ffd6a5", type: "icon", icon: "ghost" },
      { id: "ghost-5", name: "Ghost 5", color: "#c3fae8", type: "icon", icon: "ghost" },
      { id: "ghost-6", name: "Ghost 6", color: "#ffe3e3", type: "icon", icon: "ghost" },
      { id: "ghost-7", name: "Ghost 7", color: "#d0ebff", type: "icon", icon: "ghost" },
      { id: "ghost-8", name: "Ghost 8", color: "#e7c6ff", type: "icon", icon: "ghost" },
    ],
  },
  {
    id: "pokemon",
    name: "Pokemon",
    nameStyle: "fixed",
    trackColor: "#fff6d6",
    iconSize: "large",
    pieces: [
      {
        id: "pikachu",
        name: "Pikachu",
        color: "#f7d038",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/pikachu.png",
      },
      {
        id: "bulbasaur",
        name: "Bulbasaur",
        color: "#78c850",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/bulbasaur.png",
      },
      {
        id: "charmander",
        name: "Charmander",
        color: "#f08030",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/charmander.png",
      },
      {
        id: "squirtle",
        name: "Squirtle",
        color: "#6890f0",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/squirtle.png",
      },
      {
        id: "growlithe",
        name: "Growlithe",
        color: "#c84c30",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/growlithe.png",
      },
      {
        id: "magikarp",
        name: "Magikarp",
        color: "#f4a259",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/magikarp-f.png",
      },
      {
        id: "eevee",
        name: "Eevee",
        color: "#d9c2a3",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/eevee.png",
      },
      {
        id: "snorlax",
        name: "Snorlax",
        color: "#445a9c",
        type: "image",
        image: "https://img.pokemondb.net/sprites/legends-arceus/normal/snorlax.png",
      },
    ],
  },
];

export default themes;
