import {
  faGhost,
  faCar,
  faCarSide,
  faTaxi,
  faTruckPickup,
  faBusSide,
  faMotorcycle,
  faTruck,
  faVanShuttle,
  faHorse,
} from "@fortawesome/free-solid-svg-icons";

const themes = [
  {
    id: "cars",
    name: "Cars",
    nameStyle: "pooled",
    namePool: ["Turbo", "Racer", "Shift", "Blaze", "Nitro", "Axle", "Rogue", "Viper"],
    trackColor: "#dbe4ed",
    iconSize: "medium",
    pieces: [
      { id: "car-red", name: "Red", color: "#ff6b6b", type: "icon", icon: faCarSide },
      { id: "car-blue", name: "Blue", color: "#2890e6", type: "icon", icon: faCarSide },
      { id: "car-green", name: "Green", color: "#63e6be", type: "icon", icon: faTruckPickup },
      { id: "car-yellow", name: "Yellow", color: "#ffd43b", type: "icon", icon: faTruckPickup },
      { id: "car-orange", name: "Orange", color: "#ffa94d", type: "icon", icon: faTruck },
      { id: "car-purple", name: "Purple", color: "#b197fc", type: "icon", icon: faTruck },
      { id: "car-lightblue", name: "Light Blue", color: "#3ce5fc", type: "icon", icon: faBusSide },
      { id: "car-pink", name: "Pink", color: "#f783ac", type: "icon", icon: faBusSide },
      { id: "car-teal", name: "Teal", color: "#38d9a9", type: "icon", icon: faMotorcycle },
      { id: "car-grey", name: "Grey", color: "#666666", type: "icon", icon: faMotorcycle },
    ],
  },
  {
    id: "ghosts",
    name: "Ghosts",
    nameStyle: "pooled",
    namePool: ["Wraith", "Spindle", "Eerie", "Shade", "Grim", "Whisper", "Ghast", "Mourn"],
    trackColor: "#2b3b4c",
    iconSize: "medium",
    pieces: [
      { id: "ghost-1", name: "Ghost 1", color: "#9bbcff", type: "icon", icon: faGhost },
      { id: "ghost-2", name: "Ghost 2", color: "#b6f0ff", type: "icon", icon: faGhost },
      { id: "ghost-3", name: "Ghost 3", color: "#f0b3ff", type: "icon", icon: faGhost },
      { id: "ghost-4", name: "Ghost 4", color: "#ffd6a5", type: "icon", icon: faGhost },
      { id: "ghost-5", name: "Ghost 5", color: "#c3fae8", type: "icon", icon: faGhost },
      { id: "ghost-6", name: "Ghost 6", color: "#ffe3e3", type: "icon", icon: faGhost },
      { id: "ghost-7", name: "Ghost 7", color: "#d0ebff", type: "icon", icon: faGhost },
      { id: "ghost-8", name: "Ghost 8", color: "#e7c6ff", type: "icon", icon: faGhost },
    ],
  },
  {
    id: "pokemon",
    name: "Pokemon",
    nameStyle: "fixed",
    trackColor: "#fff6d6",
    iconSize: "large",
    pieces: [
      {
        id: "pikachu",
        name: "Pikachu",
        color: "#f7d038",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/pikachu.png",
      },
      {
        id: "bulbasaur",
        name: "Bulbasaur",
        color: "#78c850",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/bulbasaur.png",
      },
      {
        id: "charmander",
        name: "Charmander",
        color: "#f08030",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/charmander.png",
      },
      {
        id: "squirtle",
        name: "Squirtle",
        color: "#6890f0",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/squirtle.png",
      },
      {
        id: "growlithe",
        name: "Growlithe",
        color: "#c84c30",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/growlithe.png",
      },
      {
        id: "magikarp",
        name: "Magikarp",
        color: "#f4a259",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/magikarp-f.png",
      },
      {
        id: "eevee",
        name: "Eevee",
        color: "#d9c2a3",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/eevee.png",
      },
      {
        id: "snorlax",
        name: "Snorlax",
        color: "#445a9c",
        type: "image",
        image: "https://img.pokemondb.net/sprites/legends-arceus/normal/snorlax.png",
      },
    ],
  },
  {
    id: "horses",
    name: "Horses",
    nameStyle: "pooled",
    namePool: [
      "Buckshot",
      "Clover",
      "Sable",
      "Chestnut",
      "Midnight",
      "Dusty",
      "Maverick",
      "Willow",
      "Storm",
      "Ember",
      "Sundance",
      "Juniper",
      "Whisper",
      "Bramble",
      "Comet",
      "Canyon",
      "Biscuit",
      "Shadowfax",
      "Kestrel",
      "Boulder",
    ],
    trackColor: "#1f4f2e",
    iconSize: "medium",
    pieces: [
      { id: "horse-chestnut", name: "Chestnut", color: "#a1532b", type: "icon", icon: faHorse },
      { id: "horse-bay", name: "Bay", color: "#6b3f2a", type: "icon", icon: faHorse },
      { id: "horse-paloma", name: "Palomino", color: "#d1a867", type: "icon", icon: faHorse },
      { id: "horse-dun", name: "Dun", color: "#b18c62", type: "icon", icon: faHorse },
      { id: "horse-gray", name: "Gray", color: "#9da3a6", type: "icon", icon: faHorse },
      { id: "horse-black", name: "Black", color: "#2b2b2b", type: "icon", icon: faHorse },
      { id: "horse-roan", name: "Roan", color: "#8a6f5a", type: "icon", icon: faHorse },
      { id: "horse-cream", name: "Cream", color: "#f2d6a2", type: "icon", icon: faHorse },
    ],
  },
];

export default themes;
