import {
  faGhost,
  faCar,
  faCarSide,
  faTaxi,
  faTruckPickup,
  faBusSide,
  faMotorcycle,
  faTruck,
  faVanShuttle,
  faHorse,
} from "@fortawesome/free-solid-svg-icons";
import carsTrack from "../images/themes/cars/track_background.png";
import ghostsTrack from "../images/themes/ghosts/track_background.png";
import pokemonTrack from "../images/themes/pokemon/track_background.png";
import southParkTrack from "../images/themes/southPark/track_background.png";
import horsesTrack from "../images/themes/horses/track_background.png";
import stanImage from "../images/themes/southPark/stan.png";
import kyleImage from "../images/themes/southPark/kyle.png";
import kennyImage from "../images/themes/southPark/kenny.png";
import cartmanImage from "../images/themes/southPark/cartman.png";
import jimmyImage from "../images/themes/southPark/jimmy.png";
import buttersImage from "../images/themes/southPark/butters.png";
import tweakImage from "../images/themes/southPark/tweak.png";
import wendyImage from "../images/themes/southPark/wendy.png";

const themes = [
  {
    id: "cars",
    name: "Cars",
    fontFamily: "Audiowide",
    uiColors: {
      siteBackground: "#11161c",
      primaryBackground: "#1f2a36",
      secondaryBackground: "#344659",
      tertiaryBackground: "#e6eef7",
      textOnPrimaryBackground: "#f5f7fb",
      textOnSecondaryBackground: "#f5f7fb",
      textOnTertiaryBackground: "#141a20",
      primaryForeground: "#f5f7fb",
      secondaryForeground: "#f5f7fb",
      tertiaryForeground: "#141a20",
      darkText: "#141a20",
      lightText: "#f5f7fb",
      links: "#6ec2ff",
      primaryButtonTextColour: "#0b1117",
      secondaryButtonTextColour: "#f5f7fb",
      tertiaryButtonTextColour: "#f5f7fb",
    },
    buttonColors: {
      primary: { background: "#4fb3ff", text: "#0b1117" },
      secondary: { background: "#1f6fb8", text: "#f5f7fb" },
      tertiary: { background: "#0f3f6b", text: "#f5f7fb" },
    },
    trackBackground: carsTrack,
    trackOverlay: -3,
    nameStyle: "pooled",
    namePool: [
      "Turbo",
      "Racer",
      "Shift",
      "Blaze",
      "Nitro",
      "Axle",
      "Rogue",
      "Viper",
      "Clutch",
      "Drift",
    ],
    trackColor: "#dbe4ed",
    iconSize: "medium",
    raceNames: [
      "Warm-Up Circuit",
      "Starter Sprint",
      "Piston Point",
      "Drift District",
      "Gear Shift Alley",
      "Turbo Tarmac",
      "Octane Run",
      "Axle Arc",
      "Headlight Hustle",
      "Nitro Stretch",
      "Roadlock Rally",
      "Slipstream Street",
      "Velocity Verge",
      "Pitlane Push",
      "Torque Trail",
      "Redline Rush",
      "Apex Avenue",
      "Overtake Overpass",
      "Throttle Turn",
      "Supersonic Speedway",
      "Firewall Freeway",
      "Full-Boost Boulevard",
      "Champion Circuit",
      "Finish Line Finale",
    ],
    raceFinals: [
      {
        id: 21,
        name: "Qualifying Clash",
        laps: "2",
        forceFromPool: true,
        tiers: { easy: [7, 6, 5], normal: [8, 7, 6], hard: [9, 8, 7] },
        rewards: { first: "Qualify", second: "Qualify", third: "Qualify", fourth: "Lose" },
      },
      {
        id: 22,
        name: "Semifinal Surge",
        laps: "2",
        forceFromPool: true,
        tiers: { easy: [7, 7, 5], normal: [8, 8, 6], hard: [9, 9, 7] },
        rewards: { first: "Qualify", second: "Qualify", third: "Lose", fourth: "Lose" },
      },
      {
        id: 23,
        name: "Finals Frenzy",
        laps: "3",
        forceFromPool: true,
        tiers: { easy: [7, 7, 6], normal: [8, 8, 7], hard: [9, 9, 8] },
        rewards: { first: "Qualify", second: "Lose", third: "Lose", fourth: "Lose" },
      },
      {
        id: 24,
        name: "Championship Charge",
        laps: "3",
        forceFromPool: true,
        tiers: { easy: [8, 7, 6], normal: [9, 8, 7], hard: [10, 9, 8] },
        rewards: { first: "Win", second: "Lose", third: "Lose", fourth: "Lose" },
      },
    ],
    pieces: [
      { id: "car-red", name: "Red", color: "#ff6b6b", type: "icon", icon: faCarSide },
      { id: "car-blue", name: "Blue", color: "#2890e6", type: "icon", icon: faCarSide },
      { id: "car-green", name: "Green", color: "#0f9c27", type: "icon", icon: faTruckPickup },
      { id: "car-yellow", name: "Yellow", color: "#ffd43b", type: "icon", icon: faTruckPickup },
      { id: "car-orange", name: "Orange", color: "#ffa94d", type: "icon", icon: faTruck },
      { id: "car-purple", name: "Purple", color: "#b197fc", type: "icon", icon: faTruck },
      { id: "car-lightblue", name: "Light Blue", color: "#3ce5fc", type: "icon", icon: faBusSide },
      { id: "car-pink", name: "Pink", color: "#f783ac", type: "icon", icon: faBusSide },
      { id: "car-teal", name: "Teal", color: "#38d9a9", type: "icon", icon: faMotorcycle },
      { id: "car-grey", name: "Grey", color: "#666666", type: "icon", icon: faMotorcycle },
    ],
  },
  {
    id: "ghosts",
    name: "Ghosts",
    fontFamily: "Creepster",
    uiColors: {
      siteBackground: "#0d0b12",
      primaryBackground: "#221a2d",
      secondaryBackground: "#3a2f55",
      tertiaryBackground: "#efe8ff",
      textOnPrimaryBackground: "#f2ecff",
      textOnSecondaryBackground: "#f2ecff",
      textOnTertiaryBackground: "#1a1324",
      primaryForeground: "#f2ecff",
      secondaryForeground: "#f2ecff",
      tertiaryForeground: "#1a1324",
      darkText: "#1a1324",
      lightText: "#f2ecff",
      links: "#b58cff",
      primaryButtonTextColour: "#1a0f05",
      secondaryButtonTextColour: "#f2ecff",
      tertiaryButtonTextColour: "#16200f",
    },
    buttonColors: {
      primary: { background: "#ff8a3d", text: "#1a0f05" },
      secondary: { background: "#7a4df2", text: "#f2ecff" },
      tertiary: { background: "#8fd14f", text: "#16200f" },
    },
    trackBackground: ghostsTrack,
    trackOverlay: -5,
    nameStyle: "pooled",
    namePool: [
      "Wraith",
      "Spindle",
      "Eerie",
      "Shade",
      "Grim",
      "Whisper",
      "Ghast",
      "Mourn",
      "Specter",
      "Banshee",
    ],
    trackColor: "#2b3b4c",
    iconSize: "medium",
    raceNames: [
      "Whisper Way",
      "Cinder Crawl",
      "Shiver Sprint",
      "Wraith Walk",
      "Eerie Echo",
      "Grim Glide",
      "Haunt Hollow",
      "Shade Street",
      "Specter Sprint",
      "Ghoul Gate",
      "Phantom Pass",
      "Mourn Moor",
      "Cursed Crossing",
      "Nightveil Run",
      "Fright Flight",
      "Crypt Circuit",
      "Rattle Ridge",
      "Dread Drift",
      "Misty Mile",
      "Poltergeist Pike",
      "Banshee Boulevard",
      "Gravewind Track",
      "Shadow Speedway",
      "Final Haunting",
    ],
    raceFinals: [
      {
        id: 21,
        name: "Specter Qualifier",
        laps: "2",
        forceFromPool: true,
        tiers: { easy: [7, 6, 5], normal: [8, 7, 6], hard: [9, 8, 7] },
        rewards: { first: "Qualify", second: "Qualify", third: "Qualify", fourth: "Lose" },
      },
      {
        id: 22,
        name: "Phantom Semis",
        laps: "2",
        forceFromPool: true,
        tiers: { easy: [7, 7, 5], normal: [8, 8, 6], hard: [9, 9, 7] },
        rewards: { first: "Qualify", second: "Qualify", third: "Lose", fourth: "Lose" },
      },
      {
        id: 23,
        name: "Wraith Finals",
        laps: "3",
        forceFromPool: true,
        tiers: { easy: [7, 7, 6], normal: [8, 8, 7], hard: [9, 9, 8] },
        rewards: { first: "Qualify", second: "Lose", third: "Lose", fourth: "Lose" },
      },
      {
        id: 24,
        name: "Haunted Championship",
        laps: "3",
        forceFromPool: true,
        tiers: { easy: [8, 7, 6], normal: [9, 8, 7], hard: [10, 9, 8] },
        rewards: { first: "Win", second: "Lose", third: "Lose", fourth: "Lose" },
      },
    ],
    pieces: [
      { id: "ghost-1", name: "Ghost 1", color: "#6ad5ff", type: "icon", icon: faGhost },
      { id: "ghost-2", name: "Ghost 2", color: "#7dff8a", type: "icon", icon: faGhost },
      { id: "ghost-3", name: "Ghost 3", color: "#ff6bd6", type: "icon", icon: faGhost },
      { id: "ghost-4", name: "Ghost 4", color: "#ffb347", type: "icon", icon: faGhost },
      { id: "ghost-5", name: "Ghost 5", color: "#4dffd2", type: "icon", icon: faGhost },
      { id: "ghost-6", name: "Ghost 6", color: "#ffd93d", type: "icon", icon: faGhost },
      { id: "ghost-7", name: "Ghost 7", color: "#8e7bff", type: "icon", icon: faGhost },
      { id: "ghost-8", name: "Ghost 8", color: "#ff6f6f", type: "icon", icon: faGhost },
    ],
  },
  {
    id: "pokemon",
    name: "Pokemon",
    fontFamily: "Chewy",
    uiColors: {
      siteBackground: "#0b0f17",
      primaryBackground: "#1a2432",
      secondaryBackground: "#2e3f5a",
      tertiaryBackground: "#e9f0ff",
      textOnPrimaryBackground: "#f2f6ff",
      textOnSecondaryBackground: "#f2f6ff",
      textOnTertiaryBackground: "#121826",
      primaryForeground: "#f2f6ff",
      secondaryForeground: "#f2f6ff",
      tertiaryForeground: "#121826",
      darkText: "#121826",
      lightText: "#f2f6ff",
      links: "#7ad0ff",
      primaryButtonTextColour: "#f7f7f7",
      secondaryButtonTextColour: "#1a1a1a",
      tertiaryButtonTextColour: "#f7f7f7",
    },
    buttonColors: {
      primary: { background: "#e3363b", text: "#f7f7f7" },
      secondary: { background: "#f2b705", text: "#1a1a1a" },
      tertiary: { background: "#8f1b1f", text: "#f7f7f7" },
    },
    trackBackground: pokemonTrack,
    trackOverlay: 5,
    nameStyle: "fixed",
    trackColor: "#fff6d6",
    iconSize: "large",
    raceNames: [
      "Pallet Run",
      "Route 1 Sprint",
      "Pewter Path",
      "Cerulean Circuit",
      "Vermilion Dash",
      "Lavender Loop",
      "Celadon Sprint",
      "Saffron Surge",
      "Fuchsia Flight",
      "Cinnabar Curve",
      "Indigo Avenue",
      "Victory Road",
      "Johto Journey",
      "Ecruteak Run",
      "Goldenrod Gauntlet",
      "Mahogany Mile",
      "Blackthorn Bend",
      "Hoenn Horizon",
      "Mauville Momentum",
      "Littleroot Lap",
      "Sinnoh Sprint",
      "Unova Uprise",
      "Kalos Circuit",
      "Champion Cup",
    ],
    raceFinals: [
      {
        id: 21,
        name: "Water Derby",
        laps: "3",
        forceNames: ["Squirtle", "Magikarp"],
        tiers: { easy: [7, 5], normal: [8, 6], hard: [9, 7] },
        rewards: { first: "Qualify", second: "Qualify", third: "Lose", fourth: "Lose" },
      },
      {
        id: 22,
        name: "Forest Flurry",
        laps: "3",
        forceNames: ["Bulbasaur", "Eevee"],
        tiers: { easy: [7, 6], normal: [8, 7], hard: [9, 8] },
        rewards: { first: "Qualify", second: "Lose", third: "Lose", fourth: "Lose" },
      },
      {
        id: 23,
        name: "Fire Frenzy",
        laps: "3",
        forceNames: ["Charmander", "Growlithe"],
        tiers: { easy: [8, 6], normal: [9, 7], hard: [10, 8] },
        rewards: { first: "Qualify", second: "Lose", third: "Lose", fourth: "Lose" },
      },
      {
        id: 24,
        name: "Championship Showdown",
        laps: "5",
        forceNames: ["Pikachu", "Snorlax"],
        tiers: { easy: [8, 7], normal: [9, 8], hard: [10, 9] },
        rewards: { first: "Win", second: "Lose", third: "Lose", fourth: "Lose" },
      },
    ],
    pieces: [
      {
        id: "pikachu",
        name: "Pikachu",
        color: "#f7d038",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/pikachu.png",
      },
      {
        id: "bulbasaur",
        name: "Bulbasaur",
        color: "#78c850",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/bulbasaur.png",
      },
      {
        id: "charmander",
        name: "Charmander",
        color: "#f08030",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/charmander.png",
      },
      {
        id: "squirtle",
        name: "Squirtle",
        color: "#6890f0",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/squirtle.png",
      },
      {
        id: "growlithe",
        name: "Growlithe",
        color: "#c84c30",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/growlithe.png",
      },
      {
        id: "magikarp",
        name: "Magikarp",
        color: "#f4a259",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/magikarp-f.png",
      },
      {
        id: "eevee",
        name: "Eevee",
        color: "#d9c2a3",
        type: "image",
        image: "https://img.pokemondb.net/sprites/home/normal/eevee.png",
      },
      {
        id: "snorlax",
        name: "Snorlax",
        color: "#445a9c",
        type: "image",
        image: "https://img.pokemondb.net/sprites/legends-arceus/normal/snorlax.png",
      },
    ],
  },
  {
    id: "southPark",
    name: "South Park",
    fontFamily: "Luckiest Guy",
    uiColors: {
      siteBackground: "#1f140b",
      primaryBackground: "#3a2615",
      secondaryBackground: "#5c3a1e",
      tertiaryBackground: "#f3e1bd",
      textOnPrimaryBackground: "#f8f1e5",
      textOnSecondaryBackground: "#f8f1e5",
      textOnTertiaryBackground: "#2b1a0f",
      primaryForeground: "#f8f1e5",
      secondaryForeground: "#f8f1e5",
      tertiaryForeground: "#2b1a0f",
      darkText: "#2b1a0f",
      lightText: "#f8f1e5",
      links: "#ffd166",
      primaryButtonTextColour: "#2b1a0f",
      secondaryButtonTextColour: "#ffffff",
      tertiaryButtonTextColour: "#f8f1e5",
    },
    buttonColors: {
      primary: { background: "#d2b38a", text: "#2b1a0f" },
      secondary: { background: "#d9534f", text: "#ffffff" },
      tertiary: { background: "#1a1a1a", text: "#f8f1e5" },
    },
    trackBackground: southParkTrack,
    trackOverlay: 0,
    nameStyle: "fixed",
    trackColor: "#c9b089",
    iconSize: "large",
    raceNames: [
      "Bus Stop Blitz",
      "South Park Start",
      "Stark's Pond Sprint",
      "Schoolyard Shuffle",
      "City Wok Dash",
      "Tegridy Trail",
      "Casa Bonita Chase",
      "Kenny's Corner",
      "Cartman's Circuit",
      "Kyle's Curve",
      "Stan's Stretch",
      "Coon & Friends Run",
      "Imaginationland Mile",
      "Underpants Overdrive",
      "Goth Kids Glide",
      "Canadian Crossing",
      "Woodland Whirl",
      "SodoSopa Speed",
      "Ski Time Sprint",
      "Black Friday Blast",
      "Cows & Coasters",
      "Memberberry Run",
      "South Park Showdown",
      "Finale at the Fair",
    ],
    raceFinals: [
      {
        id: 21,
        name: "South Park Qualifier",
        laps: "3",
        forceNames: ["Kyle"],
        tiers: { easy: [5], normal: [6], hard: [7] },
        rewards: { first: "Qualify", second: "Lose", third: "Lose", fourth: "Lose" },
      },
      {
        id: 22,
        name: "Kenny's Semis",
        laps: "3",
        forceNames: ["Kenny"],
        tiers: { easy: [6], normal: [7], hard: [8] },
        rewards: { first: "Qualify", second: "Lose", third: "Lose", fourth: "Lose" },
      },
      {
        id: 23,
        name: "Stan's Finals",
        laps: "3",
        forceNames: ["Stan"],
        tiers: { easy: [7], normal: [8], hard: [9] },
        rewards: { first: "Qualify", second: "Lose", third: "Lose", fourth: "Lose" },
      },
      {
        id: 24,
        name: "Cartman Championship",
        laps: "5",
        forceNames: ["Cartman"],
        tiers: { easy: [8], normal: [9], hard: [10] },
        rewards: { first: "Win", second: "Lose", third: "Lose", fourth: "Lose" },
      },
    ],
    pieces: [
      { id: "stan", name: "Stan", color: "#2f6fd6", type: "image", image: stanImage },
      { id: "kyle", name: "Kyle", color: "#3da35a", type: "image", image: kyleImage },
      { id: "kenny", name: "Kenny", color: "#f08a24", type: "image", image: kennyImage },
      { id: "cartman", name: "Cartman", color: "#d64545", type: "image", image: cartmanImage },
      { id: "jimmy", name: "Jimmy", color: "#f2c94c", type: "image", image: jimmyImage },
      { id: "butters", name: "Butters", color: "#8fc8ff", type: "image", image: buttersImage },
      { id: "tweak", name: "Tweak", color: "#8a7d6f", type: "image", image: tweakImage },
      { id: "wendy", name: "Wendy", color: "#7a4db7", type: "image", image: wendyImage },
    ],
  },
  {
    id: "horses",
    name: "Horses",
    fontFamily: "Playwrite NZ",
    uiColors: {
      siteBackground: "#0f1512",
      primaryBackground: "#203125",
      secondaryBackground: "#395040",
      tertiaryBackground: "#e6efe2",
      textOnPrimaryBackground: "#edf3ea",
      textOnSecondaryBackground: "#edf3ea",
      textOnTertiaryBackground: "#152014",
      primaryForeground: "#edf3ea",
      secondaryForeground: "#edf3ea",
      tertiaryForeground: "#152014",
      darkText: "#152014",
      lightText: "#edf3ea",
      links: "#bfe28a",
      primaryButtonTextColour: "#1b130a",
      secondaryButtonTextColour: "#f4f6ef",
      tertiaryButtonTextColour: "#1b1b1b",
    },
    buttonColors: {
      primary: { background: "#c89b64", text: "#1b130a" },
      secondary: { background: "#7f9b4a", text: "#f4f6ef" },
      tertiary: { background: "#b8c45a", text: "#1b1b1b" },
    },
    trackBackground: horsesTrack,
    trackOverlay: 5,
    nameStyle: "pooled",
    namePool: [
      "Buckshot",
      "Clover",
      "Sable",
      "Chestnut",
      "Midnight",
      "Dusty",
      "Maverick",
      "Willow",
      "Storm",
      "Ember",
      "Sundance",
      "Juniper",
      "Whisper",
      "Bramble",
      "Comet",
      "Canyon",
      "Biscuit",
      "Shadowfax",
      "Kestrel",
      "Boulder",
      "River",
      "Cinder",
      "Pinto",
      "Starlight",
    ],
    trackColor: "#1f4f2e",
    iconSize: "medium",
    raceNames: [
      "Stable Start",
      "Meadow Mile",
      "Barnyard Burst",
      "Pasture Pace",
      "Saddle Sprint",
      "Clover Canter",
      "Thistle Track",
      "Hayfield Hustle",
      "Hoofbeat Hollow",
      "Ridge Run",
      "Dust Trail",
      "Prairie Push",
      "Windy Gallop",
      "Oak Grove Loop",
      "Timber Turn",
      "Sunset Stampede",
      "Canyon Charge",
      "Riverbend Race",
      "Stormfront Sprint",
      "Wildwood Run",
      "Frontier Flight",
      "Legend Lap",
      "Champion Canter",
      "Final Gallop",
    ],
    raceFinals: [
      {
        id: 21,
        name: "Paddock Qualifier",
        laps: "2",
        forceFromPool: true,
        tiers: { easy: [7, 6, 5], normal: [8, 7, 6], hard: [9, 8, 7] },
        rewards: { first: "Qualify", second: "Qualify", third: "Qualify", fourth: "Lose" },
      },
      {
        id: 22,
        name: "Derby Semis",
        laps: "2",
        forceFromPool: true,
        tiers: { easy: [7, 7, 5], normal: [8, 8, 6], hard: [9, 9, 7] },
        rewards: { first: "Qualify", second: "Qualify", third: "Lose", fourth: "Lose" },
      },
      {
        id: 23,
        name: "Gallop Finals",
        laps: "3",
        forceFromPool: true,
        tiers: { easy: [7, 7, 6], normal: [8, 8, 7], hard: [9, 9, 8] },
        rewards: { first: "Qualify", second: "Lose", third: "Lose", fourth: "Lose" },
      },
      {
        id: 24,
        name: "Champion's Cup",
        laps: "3",
        forceFromPool: true,
        tiers: { easy: [8, 7, 6], normal: [9, 8, 7], hard: [10, 9, 8] },
        rewards: { first: "Win", second: "Lose", third: "Lose", fourth: "Lose" },
      },
    ],
    pieces: [
      { id: "horse-chestnut", name: "Chestnut", color: "#a1532b", type: "icon", icon: faHorse },
      { id: "horse-bay", name: "Bay", color: "#6b3f2a", type: "icon", icon: faHorse },
      { id: "horse-paloma", name: "Palomino", color: "#d1a867", type: "icon", icon: faHorse },
      { id: "horse-dun", name: "Dun", color: "#b18c62", type: "icon", icon: faHorse },
      { id: "horse-gray", name: "Gray", color: "#9da3a6", type: "icon", icon: faHorse },
      { id: "horse-black", name: "Black", color: "#2b2b2b", type: "icon", icon: faHorse },
      { id: "horse-roan", name: "Roan", color: "#8a6f5a", type: "icon", icon: faHorse },
      { id: "horse-cream", name: "Cream", color: "#f2d6a2", type: "icon", icon: faHorse },
    ],
  },
];

export default themes;
